# Generated by Django 4.1.1 on 2022-09-22 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_films_options_alter_films_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='films',
        ),
    ]
