# Generated by Django 4.1.1 on 2022-09-22 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_name_review_films'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='films',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.films'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
