# Generated by Django 4.1.1 on 2022-09-22 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_genre_options_alter_genre_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='genre',
        ),
        migrations.AddField(
            model_name='films',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.genre'),
        ),
    ]
